### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rjsteinert** [open-eio/Pipe-Engine#1]
* [ ] Finish spec for sensors, pipe, and data reserviors (first draft here)
* [ ] get runtime written
* [ ] start up written
* [ ] installation written

**Comment by rjsteinert** [comment]
Here's an idea on the [command line usage](https://gist.github.com/rjsteinert/ff96e7a01438f6e5991b) of this.  A command called `thing`.
